name: CoopEra

on:
  pull_request:
    paths:
      - "coopera/**"
      - ".github/workflows/**"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coopera
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: "lts/jod"
          cache: npm
          cache-dependency-path: coopera/package-lock.json
      - run: npm ci
      - run: npm run lint:prettier:check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coopera
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: "lts/jod"
          cache: npm
          cache-dependency-path: coopera/package-lock.json
      - run: npm ci
      - run: npm run lint:eslint:check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coopera
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: "22.x"
          cache: npm
          cache-dependency-path: coopera/package-lock.json
      - run: npm ci
      - run: npm test
